### ISSUE TITLE
keyword "default" or "otherwise" instead of "else"?

### ISSUE THREAD

**Issue by B-Teague** [tc39/proposal-pattern-matching#226] opened 2021-11-01 02:16 UTC
I've seen otherwise used as a keyword in other languages.  Maybe will be a little less ambiguous?

```javascript
match (res) {
  when ({ pages, data }) if (pages > 1) { … }
  when ({ pages, data }) if (pages === 1) { … }
  else { … }
}
```
vs
```javascript
match (res) {
  when ({ pages, data }) if (pages > 1) { … }
  when ({ pages, data }) if (pages === 1) { … }
  otherwise { … }
}
```
vs
```javascript
match (res) {
  when ({ pages, data }) if (pages > 1) { … }
  when ({ pages, data }) if (pages === 1) { … }
  default { … }
}
```

**Comment by ljharb** [comment] 2021-11-01 04:01
Duplicate of #208.

**Closed by ljharb** 2021-11-01 04:01 UTC
